In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')# Reading the Dataset

In [3]:
dataset.head(133)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,46.0,80.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,160.000000,...,27.000000,8100.000000,3.200000,yes,no,no,poor,poor,yes,yes
129,46.0,110.000000,d,0.0,0.0,normal,normal,notpresent,notpresent,130.000000,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,yes
130,46.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,123.000000,...,50.000000,6300.000000,4.800000,no,no,no,yes,poor,no,no
131,46.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,102.000000,...,44.000000,11000.000000,5.400000,no,no,no,yes,poor,no,no
132,46.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,43.000000,5700.000000,6.500000,no,no,no,yes,poor,no,no

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [10]:
dep=dataset['classification_yes']

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [12]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [15]:
X_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60.0,100.0,0.0,3.0,263.0,27.000000,1.300000,135.000000,4.300000,12.700000,...,1,1,0,0,1,1,1,1,0,0
218,57.0,80.0,0.0,0.0,120.0,48.000000,1.600000,137.528754,4.627244,11.300000,...,1,1,0,0,1,1,0,1,0,0
101,42.0,70.0,0.0,0.0,75.0,31.000000,1.200000,141.000000,3.500000,16.500000,...,1,1,0,0,0,0,0,1,0,0
311,66.0,70.0,1.0,0.0,248.0,30.000000,1.700000,138.000000,5.300000,12.518156,...,1,1,0,0,1,1,0,1,0,0
194,55.0,80.0,0.0,0.0,146.0,57.482105,3.077356,137.528754,4.627244,9.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68.0,70.0,0.0,0.0,98.0,86.000000,4.600000,135.000000,3.400000,9.800000,...,1,1,0,0,1,1,1,0,1,0
192,54.0,90.0,1.0,0.0,150.0,18.000000,1.200000,140.000000,4.200000,12.518156,...,1,0,0,0,0,0,0,0,1,1
117,45.0,80.0,0.0,0.0,107.0,15.000000,1.000000,141.000000,4.200000,11.800000,...,1,0,0,0,0,0,0,1,0,0
47,30.0,80.0,0.0,0.0,89.0,42.000000,0.500000,139.000000,5.000000,16.700000,...,1,1,0,0,0,0,0,1,0,0
172,51.0,60.0,0.0,0.0,129.0,25.000000,1.200000,139.000000,5.000000,17.200000,...,1,1,0,0,0,0,0,1,0,0

In [16]:
X_test

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
132,46.000000,70.0,0.0,0.0,100.000000,47.0,0.5,142.000000,3.500000,16.400000,...,1,1,0,0,0,0,0,1,0,0
309,66.000000,90.0,2.0,0.0,153.000000,76.0,3.3,137.528754,4.627244,12.518156,...,1,1,0,1,0,0,0,0,0,0
334,69.000000,70.0,0.0,0.0,83.000000,42.0,1.2,139.000000,3.700000,16.200000,...,1,1,0,0,0,0,0,1,0,0
196,55.000000,100.0,1.0,4.0,297.000000,53.0,2.8,139.000000,4.500000,11.200000,...,1,1,0,0,1,1,0,1,0,0
246,60.000000,90.0,2.0,0.0,105.000000,53.0,2.3,136.000000,5.200000,11.100000,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,71.000000,70.0,0.0,0.0,81.000000,18.0,0.8,145.000000,5.000000,14.700000,...,1,1,0,0,0,0,0,1,0,0
168,50.000000,80.0,0.0,0.0,137.000000,46.0,0.8,139.000000,5.000000,14.100000,...,1,1,0,0,0,0,0,1,0,0
150,48.000000,100.0,0.0,0.0,103.000000,79.0,5.3,135.000000,6.300000,6.300000,...,1,1,0,0,1,0,1,0,0,0
392,51.492308,60.0,3.0,0.0,148.112676,34.0,1.2,137.528754,4.627244,10.800000,...,0,0,0,0,0,0,0,1,0,0
66,34.000000,60.0,0.0,0.0,91.000000,49.0,1.2,135.000000,4.500000,13.500000,...,1,1,0,0,0,0,0,1,0,0

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [18]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\rousan\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.95697403 0.97917804 0.97293314 0.98479084
        nan        nan 0.97580668 0.98231422 0.96999473 0.97923869]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [19]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [20]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9849624060150376

In [16]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}

In [21]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[50  1]
 [ 1 81]]

In [22]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        51
           1       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [23]:
from sklearn.metrics import roc_auc_score

auc=roc_auc_score(y_test,grid.decision_function(X_test))

print("ROC_AUC:", round(auc,4))

AttributeError: 'RandomForestClassifier' object has no attribute 'decision_function'

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002372,0.004745,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000420,0.000514,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.065258,0.007389,0.015563,0.000248,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.969697,0.957746,0.918033,0.969697,0.969697,0.956974,0.020013,8
3,0.559374,0.010516,0.045682,0.004079,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.969697,0.971429,0.984615,0.985075,0.985075,0.979178,0.007058,4
4,0.056593,0.007129,0.014908,0.002000,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.969697,0.956522,0.968750,0.969697,1.000000,0.972933,0.014425,6
5,0.535587,0.007221,0.047700,0.000374,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.985507,0.968750,0.969697,1.000000,0.984791,0.013772,1
6,0.003232,0.006464,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.003223,0.006446,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.059768,0.006270,0.013917,0.007060,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.985075,0.971429,0.952381,0.985075,0.985075,0.975807,0.012850,5
9,0.466198,0.015461,0.046519,0.002320,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.957746,0.968750,0.985075,1.000000,0.982314,0.016857,2
10,0.063846,0.000479,0.012648,0.006334,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.985075,0.957746,0.952381,0.969697,0.985075,0.969995,0.013529,7
11,0.397797,0.010414,0.025494,0.007766,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.957746,0.968750,0.969697,1.000000,0.979239,0.017464,3

In [31]:
print("Best parameters:", grid.best_params_)
print("Best validation weighted F1:", grid.best_score_)
print("Best model:", grid.best_estimator_)

Best parameters: {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}
Best validation weighted F1: 0.9847908432147563
Best model: RandomForestClassifier(max_features='log2')

In [33]:
# Create the results table
table = pd.DataFrame(grid.cv_results_)

# Export to CSV
table.to_csv("RF_Grid_Results.csv", index=False)

print("CSV file saved successfully.")

CSV file saved successfully.